In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [2]:
import pandas as pd

X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv").squeeze("columns")
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze("columns")

In [3]:
models={
    "LogisticRegression":LogisticRegression(random_state=42),
    "DecisionTreeClassifier":DecisionTreeClassifier(random_state=42),
    "RandomForestClassifier":RandomForestClassifier(random_state=42)
}

In [4]:
results=[]

for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    y_prob=model.predict_proba(X_test)[:,1]

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_prob)

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ])

In [5]:
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "ROC-AUC"
    ]
)
results_df = results_df.round(4)
results_df

                    Model  Accuracy  Precision  Recall  F1-Score  ROC-AUC
0      LogisticRegression    0.7875     0.6206  0.5160    0.5635   0.8319
1  DecisionTreeClassifier    0.7335     0.4988  0.5481    0.5223   0.6739
2  RandomForestClassifier    0.7846     0.6300  0.4599    0.5317   0.8179

In [6]:
train_test_results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_accuracy = accuracy_score(y_train, train_pred)
    test_accuracy = accuracy_score(y_test, test_pred)

    train_test_results.append([
        name,
        train_accuracy,
        test_accuracy
    ])

In [7]:
train_test_df = pd.DataFrame(
    train_test_results,
    columns=[
        "Model",
        "Training Accuracy",
        "Testing Accuracy"
    ]
)

train_test_df = train_test_df.round(4)

train_test_df

                    Model  Training Accuracy  Testing Accuracy
0      LogisticRegression             0.8085            0.7875
1  DecisionTreeClassifier             0.9977            0.7335
2  RandomForestClassifier             0.9977            0.7846